# Generated by Django 4.0.4 on 2022-05-20 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='datecreated',
        ),
    ]
