# Generated by Django 4.0.4 on 2022-05-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
