# Generated by Django 4.0.4 on 2022-06-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_tag_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
