# Generated by Django 4.0.4 on 2022-06-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_customer_profile_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_cv',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_cv',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
