# Generated by Django 4.0.4 on 2022-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_remove_customer_user_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_cv',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
